In [17]:
import pandas as pd
import numpy as np

In [18]:
# Montar Google Drive en Colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
%cd /content/drive/MyDrive/Riesgos

/content/drive/MyDrive/Riesgos

In [20]:
ls

riesgo.xlsx

In [22]:
df = pd.read_excel("riesgo.xlsx")
df

,Customer_ID,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,CUS_0x1000,Alistair Barrf,17.375000,913-74-1218,Lawyer,30625.940,2706.161667,6.0,5.0,27,...,Bad,1562.91,33.477546,10.458333,Yes,42.941090,158.549735,High_spent_Medium_value_payments,335.375341,0
1,CUS_0x1009,Arunah,25.750000,063-67-6938,Mechanic,52312.680,4250.390000,6.0,5.0,17,...,Standard,202.68,29.839984,30.714286,Yes,108.366467,146.679378,High_spent_Medium_value_payments,428.743155,1
2,CUS_0x100b,Shirboni,18.500000,238-62-0395,Media_Manager,113781.390,9549.782500,1.0,4.0,1,...,Good,1030.20,34.841449,15.571429,No,0.000000,505.386526,High_spent_Large_value_payments,781.229776,0
3,CUS_0x1011,Schneyerh,43.875000,793-05-8223,Doctor,58918.470,5208.872500,3.0,3.0,17,...,Standard,473.14,27.655897,15.541667,Yes,123.434939,311.060914,Low_spent_Medium_value_payments,332.642837,1
4,CUS_0x1013,Cameront,43.750000,930-49-9615,Mechanic,98620.980,7962.415000,3.0,3.0,6,...,Good,1233.51,31.933940,17.535714,No,228.018084,355.442408,High_spent_Medium_value_payments,472.781009,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,CUS_0xff3,Somervilled,55.000000,726-35-5322,Scientist,17032.785,1176.398750,0.0,6.0,2,...,Good,1229.08,32.889398,17.000000,No,33.299764,83.918549,Low_spent_Small_value_payments,271.671562,1
12496,CUS_0xff4,Poornimaf,36.857143,655-05-7666,Entrepreneur,25546.260,2415.855000,8.0,7.0,14,...,Standard,758.44,32.598257,18.440476,Yes,101.328637,152.775690,Low_spent_Small_value_payments,259.981173,1
12497,CUS_0xff6,Shieldsb,18.625000,541-92-8371,Doctor,117639.920,9727.326667,5.0,6.0,1,...,Good,338.30,33.258053,24.625000,No,126.638453,655.228203,High_spent_Small_value_payments,667.322417,1
12498,CUS_0xffc,Brads,17.375000,226-86-7294,Musician,60877.170,5218.097500,6.0,8.0,27,...,Bad,1300.13,34.722108,12.861111,Yes,272.809169,156.172974,High_spent_Large_value_payments,339.951771,0
12499,CUS_0xffd,Damouniq,29.250000,832-88-8320,Scientist,41398.440,3749.870000,8.0,7.0,13,...,Standard,1701.88,31.894261,18.458333,Yes,182.976649,168.822507,High_spent_Medium_value_payments,290.687843,1

In [23]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               12500 non-null  object
 1   Name                      12500 non-null  object
 2   Age                       12500 non-null  float64
 3   SSN                       12500 non-null  object
 4   Occupation                12500 non-null  object
 5   Annual_Income             12500 non-null  float64
 6   Monthly_Inhand_Salary     12500 non-null  float64
 7   Num_Bank_Accounts         12500 non-null  float64
 8   Num_Credit_Card           12500 non-null  float64
 9   Interest_Rate             12500 non-null  int64
 10  Num_of_Loan               12500 non-null  int64
 11  Type_of_Loan              11074 non-null  object
 12  Delay_from_due_date       12500 non-null  float64
 13  Num_of_Delayed_Payment    12500 non-null  float64
 14  Changed_Credit_Limit      12500 non-null  float64
 15  Num_Credit_Inquiries      12500 non-null  float64
 16  Credit_Mix                12500 non-null  object
 17  Outstanding_Debt          12500 non-null  float64
 18  Credit_Utilization_Ratio  12500 non-null  float64
 19  Credit_History_Age        12500 non-null  float64
 20  Payment_of_Min_Amount     12500 non-null  object
 21  Total_EMI_per_month       12500 non-null  float64
 22  Amount_invested_monthly   12500 non-null  float64
 23  Payment_Behaviour         12500 non-null  object
 24  Monthly_Balance           12500 non-null  float64
 25  Credit_Score              12500 non-null  int64
dtypes: float64(15), int64(3), object(8)
memory usage: 2.5+ MB
None

In [25]:
print(df.isnull().sum())

Customer_ID                    0
Name                           0
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary          0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                1426
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit           0
Num_Credit_Inquiries           0
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age             0
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly        0
Payment_Behaviour              0
Monthly_Balance                0
Credit_Score                   0
dtype: int64

In [26]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,12500.0,33.311294,10.760177,14.000000,24.415179,33.000000,41.750000,56.000000
Annual_Income,12500.0,50505.123449,38300.762656,7005.930000,19342.972500,36999.705000,71683.470000,179987.280000
Monthly_Inhand_Salary,12500.0,4198.468568,3187.142979,303.645417,1625.744479,3097.016667,5961.664375,15204.633333
Num_Bank_Accounts,12500.0,5.368828,2.592493,0.000000,3.000000,5.375000,7.000000,10.500000
Num_Credit_Card,12500.0,5.533620,2.066040,0.500000,4.000000,5.000000,7.000000,10.875000
Interest_Rate,12500.0,14.532080,8.741636,1.000000,7.000000,13.000000,20.000000,34.000000
Num_of_Loan,12500.0,3.532880,2.446442,0.000000,2.000000,3.000000,5.000000,9.000000
Delay_from_due_date,12500.0,21.068780,14.772965,-2.000000,9.875000,17.875000,28.000000,63.250000
Num_of_Delayed_Payment,12500.0,13.338642,6.153148,0.000000,9.000000,13.750000,18.175000,26.375000
Changed_Credit_Limit,12500.0,10.465068,6.445141,0.500000,5.493750,9.370000,14.656250,31.115000
Num_Credit_Inquiries,12500.0,5.779694,3.707936,0.000000,3.000000,5.250000,8.500000,16.375000
Outstanding_Debt,12500.0,1426.220376,1155.169458,0.230000,566.072500,1166.155000,1945.962500,4998.070000
Credit_Utilization_Ratio,12500.0,32.285069,2.060154,25.476634,30.854492,32.241830,33.600168,42.395301
Credit_History_Age,12500.0,18.433820,8.304817,0.375000,12.041667,18.238095,25.125000,33.380952
Total_EMI_per_month,12500.0,107.698610,118.990964,0.000000,30.333649,68.102176,151.220882,1515.158986
Amount_invested_monthly,12500.0,195.751837,136.847120,14.528879,97.690749,152.081485,257.566585,1005.847285
Monthly_Balance,12500.0,403.120320,175.476887,92.841401,284.546710,338.491580,465.372970,1349.264887
Credit_Score,12500.0,0.845200,0.697994,0.000000,0.000000,1.000000,1.000000,2.000000

In [27]:
print(df.dtypes)

Customer_ID                  object
Name                         object
Age                         float64
SSN                          object
Occupation                   object
Annual_Income               float64
Monthly_Inhand_Salary       float64
Num_Bank_Accounts           float64
Num_Credit_Card             float64
Interest_Rate                 int64
Num_of_Loan                   int64
Type_of_Loan                 object
Delay_from_due_date         float64
Num_of_Delayed_Payment      float64
Changed_Credit_Limit        float64
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt            float64
Credit_Utilization_Ratio    float64
Credit_History_Age          float64
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly     float64
Payment_Behaviour            object
Monthly_Balance             float64
Credit_Score                  int64
dtype: object

debemos cmabiar u object tenemos que numerilizarlos

In [28]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'SSN', 'Occupation', 'Annual_Income',
       'Monthly_Inhand_Salary', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

para borra las columnas

vamos a quitar las columnas el Customerid

In [29]:
columnas_eliminar = ['Customer_ID', 'Name', 'SSN', 'Type_of_Loan']
df.drop(columnas_eliminar, axis=1, inplace=True)

In [32]:
columnas_objeto = df.select_dtypes(include='object').columns
print(columnas_objeto.tolist())

['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour']

In [33]:
# Contar instancias (filas) de cada columna tipo object
for columna in df.select_dtypes(include='object').columns:
    print(f'\n📌 Columna: {columna}')
    print(f'   Total instancias: {df[columna].count()}')
    print(f'   Valores únicos:   {df[columna].nunique()}')
    print(df[columna].value_counts())
    print('-' * 50)

📌 Columna: Occupation
   Total instancias: 12500
   Valores únicos:   15
Occupation
Lawyer           887
Engineer         858
Architect        853
Mechanic         847
Scientist        843
Accountant       843
Media_Manager    840
Developer        840
Teacher          834
Entrepreneur     831
Doctor           821
Journalist       817
Manager          804
Musician         794
Writer           788
Name: count, dtype: int64
--------------------------------------------------

📌 Columna: Credit_Mix
   Total instancias: 12500
   Valores únicos:   3
Credit_Mix
Standard    5731
Good        3798
Bad         2971
Name: count, dtype: int64
--------------------------------------------------

📌 Columna: Payment_of_Min_Amount
   Total instancias: 12500
   Valores únicos:   3
Payment_of_Min_Amount
Yes    7360
No     5031
NM      109
Name: count, dtype: int64
--------------------------------------------------

📌 Columna: Payment_Behaviour
   Total instancias: 12500
   Valores únicos:   6
Payment_Behaviour
Low_spent_Small_value_payments      3860
High_spent_Medium_value_payments    3086
High_spent_Large_value_payments     2726
Low_spent_Medium_value_payments     1136
High_spent_Small_value_payments      972
Low_spent_Large_value_payments       720
Name: count, dtype: int64
--------------------------------------------------

In [34]:
# Ver la cardinalidad de Credit_Mix
print('Cardinalidad (# de valores únicos):', df['Credit_Mix'].nunique())
print('\nValores únicos:', df['Credit_Mix'].unique())

Cardinalidad (# de valores únicos): 3

Valores únicos: ['Bad' 'Standard' 'Good']

Vamos a eliminar la profesion y el comportamiento del pago , tiene un cardinalidad alta pero basicamnete para agilizar el ejercicisio

In [38]:
df.drop(columns=['Payment_Behavior'], axis=1, inplace=True)

KeyError: "['Payment_Behavior'] not found in axis"

In [37]:
# Mostrar los 10 primeros datos de la columna Credit_Score
df['Credit_Score'].head(10)

0    0
1    1
2    0
3    1
4    1
5    2
6    0
7    1
8    2
9    1
Name: Credit_Score, dtype: int64

In [39]:
# Ver los valores únicos de Credit_Score
df['Credit_Score'].unique()
df

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,17.375000,Lawyer,30625.940,2706.161667,6.0,5.0,27,2,62.250,25.000000,...,Bad,1562.91,33.477546,10.458333,Yes,42.941090,158.549735,High_spent_Medium_value_payments,335.375341,0
1,25.750000,Mechanic,52312.680,4250.390000,6.0,5.0,17,4,7.250,17.857143,...,Standard,202.68,29.839984,30.714286,Yes,108.366467,146.679378,High_spent_Medium_value_payments,428.743155,1
2,18.500000,Media_Manager,113781.390,9549.782500,1.0,4.0,1,0,13.500,7.375000,...,Good,1030.20,34.841449,15.571429,No,0.000000,505.386526,High_spent_Large_value_payments,781.229776,0
3,43.875000,Doctor,58918.470,5208.872500,3.0,3.0,17,3,27.250,14.500000,...,Standard,473.14,27.655897,15.541667,Yes,123.434939,311.060914,Low_spent_Medium_value_payments,332.642837,1
4,43.750000,Mechanic,98620.980,7962.415000,3.0,3.0,6,3,12.500,8.428571,...,Good,1233.51,31.933940,17.535714,No,228.018084,355.442408,High_spent_Medium_value_payments,472.781009,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,55.000000,Scientist,17032.785,1176.398750,0.0,6.0,2,3,12.250,8.625000,...,Good,1229.08,32.889398,17.000000,No,33.299764,83.918549,Low_spent_Small_value_payments,271.671562,1
12496,36.857143,Entrepreneur,25546.260,2415.855000,8.0,7.0,14,5,15.875,12.125000,...,Standard,758.44,32.598257,18.440476,Yes,101.328637,152.775690,Low_spent_Small_value_payments,259.981173,1
12497,18.625000,Doctor,117639.920,9727.326667,5.0,6.0,1,2,-0.125,4.000000,...,Good,338.30,33.258053,24.625000,No,126.638453,655.228203,High_spent_Small_value_payments,667.322417,1
12498,17.375000,Musician,60877.170,5218.097500,6.0,8.0,27,8,45.375,16.250000,...,Bad,1300.13,34.722108,12.861111,Yes,272.809169,156.172974,High_spent_Large_value_payments,339.951771,0
12499,29.250000,Scientist,41398.440,3749.870000,8.0,7.0,13,6,23.000,11.428571,...,Standard,1701.88,31.894261,18.458333,Yes,182.976649,168.822507,High_spent_Medium_value_payments,290.687843,1

In [41]:
X = df.drop(columns=["Credit_Score"])
Y = to_categorical(df["Credit_Score"],num_classes=3)

NameError: name 'to_categorical' is not defined